### ISSUE TITLE
ping pong bench fail

### ISSUE THREAD

**Issue by BowenXiao1999** [Fugoes/yaay-rs#1]
run `time ./target/release/mio_ping_pong 127.0.0.1:12346 8 1`

get `Connection reset by peer`
```
thread 'yaay-mt-runtime-worker-7' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }', yaay-tests/src/mio_ping_pong.rs:75:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'yaay-mt-runtime-worker-6' panicked at 'thread 'thread 'yaay-mt-runtime-worker-1called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }yaay-mt-runtime-worker-0thread '', ' panicked at 'yaay-mt-runtime-worker-4yaay-tests/src/mio_ping_pong.rs' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }' panicked at ':', called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }75yaay-tests/src/mio_ping_pong.rs', ::yaay-tests/src/mio_ping_pong.rs', 51:75yaay-tests/src/mio_ping_pong.rs
75:::755151:thread '
51
yaay-mt-runtime-worker-2
' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }', yaay-tests/src/mio_ping_pong.rsyaay-mt-runtime-worker-5:75' panicked at ':called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }51', 
yaay-tests/src/mio_ping_pong.rs:75:51
thread 'yaay-mt-runtime-worker-3' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }', yaay-tests/src/mio_ping_pong.rs:75:51
./target/release/mio_ping_pong 127.0.0.1:12346 8 1  0.11s user 0.10s system 167% cpu 0.122 total

```

Any idea for setting up environment for this bench?

**Comment by Fugoes** [comment]
try:
```
ulimit -n 10000
```
As stated in the README:
> To run these programs, some system limits need to be adjusted (and these programs does no error handling :)).
